export const zh = {
    common: {
        yes:'确认',
        no:'取消',
        success:'成功'
    },
    pagination: {
        total:'共',
        item:'条'
    },
    message: {
        register: '注册成功即将跳转',
        smscode: '发送成功,注意查收',
        login:'登录成功即将跳转',
        forget:'修改成功'
    },
    login: {
        title:'用户登录',
        form1:'邮箱地址',
        placeholder1:'请输入邮箱',
        message1:'请输入正确的邮箱',
        form2:'密码',
        placeholder2:"请输入密码",
        tips:'登录即代表同意',
        tips2:'服务条款',
        button1:'忘记密码',
        message3:'请勾选服务条款',
        button2:'登录',
        content:'没有账户?',
        content2:'去注册'
    },
    register: {
        title:'用户注册',
        form1:'邮箱地址',
        placeholder1:'请输入邮箱',
        message1:'请输入正确的邮箱',
        form2:'邮箱验证码',
        code:'发送验证码',
        placeholder2:'请输入验证码',
        message2:'请输入验证码',
        message3:'请勾选服务条款',
        tip:'如果没有收到验证码，请检查邮箱的垃圾箱',
        form3:'密码',
        placeholder3:'请输入密码',
        form4:'重复密码',
        placeholder4:"两次输入的密码不一致",
        form5:'邀请码',
        placeholder5:'请输入邀请码(可留空)',
        tip1:'注册即代表同意',
        tip2:'服务条款',
        button:'注册',
        content:'已有账号?',
        content2:'登录'
    },
    forgetpassword: {
        title:'修改密码',
        form1:'邮箱地址',
        placeholder1:'请输入邮箱',
        message1:'请输入正确的邮箱',
        form2:'邮箱验证码',
        code:'发送验证码',
        placeholder2:'请输入验证码',
        message2:'请输入验证码',
        message3:'请勾选服务条款',
        tip:'如果没有收到验证码，请检查邮箱的垃圾箱',
        form3:'密码',
        placeholder3:'请输入密码',
        form4:'重复密码',
        placeholder4:"两次输入的密码不一致",
        tip1:'同意',
        tip2:'服务条款',
        button:'确认修改',
        content:'已完成设置?',
        content2:'登录'
    },
    nav: {
        button:'登录',
        button1:'注册',
        item1:'主页',
        item2:'服务',
        item3:'价格'
    },
    footer: {
        title: '凭借全球广泛的网络资源布局和深刻的业务洞察，IPdodo将不断精进产品与服务品质，与合作伙伴坚定共拓全球化业务',
        subtitle1:'政策',
        subtitle1_title1:'Miya用户协议',
        subtitle1_title2:'Miya隐私协议',
        subtitle2:'友情链接',
        subtitle2_title1:'hubstudio Fingerprint Browser',
        subtitle2_title2:'mulogin Fingerprint Browser',
        subtitle2_title3:'Bit Fingerprint Browser',
        subtitle2_title4:'AdsPower',
        subtitle2_title5:'vmlogin Fingerprint Browser',
        subtitle2_title6:'yunlark Browser',
        subtitle2_title7:'nest Browser',
        subtitle2_title8:'MoreLogin Fingerprint Browser',
        subtitle2_title9:'Cross-border King (Cross-border Marketing software)',
        subtitle2_title10:'luban',
        subtitle2_title11:'firebrowser',
        item1:'电话',
        item2:'邮箱',
        item3:'在线时间',
        item4:'办公地址'
    },
    home: {
        first: {
            title:'为您提供',
            title2:'最专业',
            title3:'数据采集​​解决方案',
            subtitle1:'专业的全球住宅代理',
            subtitle1_detail1:'超过',
            subtitle1_detail2:'60,000,000+',
            subtitle1_detail3:'IPS',

            subtitle2:'全球主要城市精准定位',
            subtitle2_detail1:'参与',
            subtitle2_detail2:'爬虫，电子商务',
            subtitle2_detail3:'以及其他业务需求',
            subtitle3:'动静随意切换',
            subtitle3_detail1:'支持',
            subtitle3_detail2:'http,https,socks5',
            subtitle3_detail3:'便于使用',
        },
        second: {
            title: '为您的企业提供可靠的数据采集解决方案',
            subtitle1:'住宅代理',
            content1:'无需IP封锁的真实抓取模式',
            subtitle2:'领先技术',
            content2:'基于人工智能和机器学习的解决方案，可有效捕获信息',
            subtitle3:'实时爬虫',
            content3:'从搜索引擎和电子商务网站提取数据',
            subtitle4:'实时爬虫',
            content4:'从搜索引擎和电子商务网站提取数据',
            item1:'100% 交付',
            item2:'国家/地区和 ASN 筛选',
            item3:'自适应解析器'
        },
        third: {
           title: 'MIYAIP服务全球200多个国家',
        },
        fourth: {
            title: '更优惠的价格',
            subtitle1: '定位',
            subtitle1_1:'地区',
            subtitle1_type:'动态住宅',
            subtitle1_content:'按流量计费，不限IP数量',

            subtitle2: '1 IP/月',
            subtitle2_1:'/独享',
            subtitle2_type:'静态住宅',
            subtitle2_content:'按流量计费，不限IP数量',

            subtitle3: '定位',
            subtitle3_1:'地区',
            subtitle3_type:'动态住宅',
            subtitle3_content:'按流量计费，不限IP数量',
            data:'数据',
            button:'立刻购买'
        },
        fifth: {
            title: '选择我们的理由',
            subtitle:'超过500个国家和地区的IP，更快的速度，最好的服务器，给您更好的服务',
            item1:'速度更快',
            item2:'更稳定的服务',
            item3:'独家代理',
            item4:'快速集成'
        }
    },
    usercenter: {
        
        nav: {
            menu1:'仪表盘',
            menu1_subtitle1:'动态住宅',
            menu1_subtitle2:'静态住宅',
            menu2:'动态住宅',
            menu2_subtitle1:'代理生成-国家',
            menu2_subtitle2:'代理生成',
            menu2_subtitle3:'购买流量',
            menu3:'静态住宅',
            menu3_subtitle1:'购买代理',
            menu3_subtitle2:'已购明细',
            menu4:'历史订单',
            menu5:'帮助中心',
            menu5_subtitle1:'帮助文档',
            menu5_subtitle2:'服务条款',
            menu6:'开发者API',
            menu7:'奖励推广'
        },
        userinfo: {
            button:'修改密码',
            content:'账户余额',
            button1:'USDT充值',
            button2:'退出登录',
            title:'修改密码',
            recharge: {
                title:'USDT充值',
                tip:'USDT交易需要确认时间，i请转账后等待10-20分钟后提交单号充值',
                form1:'充值类型',
                content1:'TRC20',
                form2:'付款地址',
                content2:'TLdKPrs3aAFx1d7628gSE3naod2MQzimng',
                code: '付款地址二维码',
                form3:'交易流水号',
                content3:'请输入流水交易号',
                tip2:'充值后填写交易流水号，网站会显示您充值的USDT余额',
                button:'提交'
            }
        },
        dashboardDy: {
            title: '仪表板-动态住宅代理',
            subtitle1:'定位国家',
            button:'代理生成',
            charttitle:'总流量 [Gb]',
            usedFlow:'已使用流量 [Gb]',
            resetFlow:'剩余流量 [Gb]',
            button2:'购买流量',
            subtitle2:'流量使用趋势',
            column1:'ID',
            column2:'类型',
            column3:'IP',
            column4:'地点',
            column5:'日期',
            column6:'User-Agent'
        },
        dashboardStatic: {
            title: '仪表板-静态住宅代理',
            subtitle1:'全部代理',
            subtitle2:'独享代理',
            subtitle3:'共享代理',
            unit:'个',
            tableTitle:'流量使用趋势',
            button:'更多',
            column1:'Socks5 二维码',
            column2:'过期时间',
            column3:'类型',
            column4:'原始IP(Socks5)',
            column5:'原始IP(http)',
            column6:'中转代理(Socks5)',
        },
        proxycity: {
            form1:'池类型',
            placeholder:'请选择',
            countryform:'全球随机',
            min:'分钟',
            IPform:'每次请求更换',
            cityform:'随机选择',
            form2:'国家',
            form3:'省/州',
            form4:'城市',
            form5:'IP固定切换时间',
            form6:'生成类型',
            form7:'数量',
            subtitle:'API切换代理按钮',
            tip:'',
            switch:'如有必要，请单击',
            button1:'生成',
            button2:'导出成API',
            copy:'复制',
            tip2:'输入或粘贴代理文本生成二维码(一次只能将一条代理文本转为二维码)',
            button3:'生成二维码',
            tip3:'生成socks5二维码(可用Shadowrockt直接扫码使用)',
            tip4:'暂无二维码',
            title:'代理生成',
            button4:'购买流量',
            charttitle:'总流量 [Gb]',
            usedFlow:'已使用流量 [Gb]',
            resetFlow:'剩余流量 [Gb]',
        },
        purchasetraffic: {
            title:'购买流量',
            content1:'定位国家',
            content2:'永不过期',
            content3:'专属IP池',
            content4:'2个超大IP池，合计IP数量超6000万',
            content5:'无限并发',
            content6:'可变时效',
            content7:'不支持',
            tip:'最大100G',
            subtitle1:'类别',
            subtitle2:'单价',
            subtitle3:'时长',
            subtitle4:'IP池',
            subtitle5:'动态IP池数量',
            subtitle6:'并发性',
            subtitle7:'城市定位',
            subtitle8:'流量',
            subtitle9:'时效可变性',
            content11:'定位城市',
            content12:'永不过期',
            content13:'专属IP池',
            content14:'2个超大IP池，合计IP数量超6000万',
            content15:'无限并发',
            content16:'可变时效',
            content17:'不支持',
            tip2:'未选择流量类别',
            label:'折扣码',
            tip3:'请输入折扣码',
            tip4:'已选择定位',
            tip5:'购买流量',
            tip6:'买它',
            tip7:'国家',
            tip8:'城市',
            button:'前去了解',
            button_title:'请联系我们了解更多特别套餐'
        },
        pay: {
            title:'总金额',
            button1:'USDT余额',
            button2:'其它支付方式',
            pay1:'支付宝',
            pay2:'微信',
            button3:'确认支付',
            button4:'余额不足',
            button5:'取消'
        },
        purchaseproxy: {
            title:'购买代理',
            subtitle1:'需求国家',
            subtitle2:'IP授权类型',
            subtitle3:'IP购买时长',
            subtitle4:'IP购买数量',
            subtitle4_tip:'(最大数量100)',
            subtitle5:'折扣码',
            subtitle2_1:'独享',
            subtitle2_2:'共享',
            subtitle2_tip:'独享单价',
            subtitle2_tip1:' /IP/月',
            unit:'天',
            subtitle5_content:'请输入折扣码',
            content1:'已选择IP',
            unit2:'个'
        },
        historyorder: {
            title:'历史订单',
            subtitle1:'全部[订单]',
            subtitle2:'已支付[订单]',
            subtitle3:'未支付[订单]',
            select1:'全部',
            select2:'未支付',
            select3:'已支付',
            placeholder:'请输入id查询',
            column1:'订单ID',
            column2:'订单名称',
            column3:'总金额',
            column4:'订单状态',
            column5:'订购时间',
            column6:'支付时间'
        },
        serviceterms: {
            title:'服务条款',
            subtitle1:'介绍',
            subtitle1_content1:'写在本网页上的这些网站标准条款和条件将管理您对我们网站的使用，IPLOONG可访问www.iploong.com。\n这些条款将完全适用并影响您对本网站的使用。通过使用本网站，您同意接受此处所写的所有条款和条件。如果您不同意本网站的任何标准条款和条件，则不得使用本网站。 \nIPLOONG不会故意从13岁以下的人那里收集个人信息，无论是在线还是离线。如果您未满18岁，只有在父母或监护人的许可下，您才能使用www.iploong.com。',
            subtitle2:'退款政策',
            subtitle2_content1:'这些代理从您收到它们时起就处于活动状态，所有代理在交付前都经过测试，交付时完全正常工作。代理根据产品名称和描述指定为数据中心或住宅，不由客户决定。我们不负责在发布期间因使用不当和设置不正确而被禁止。我们保留停用带宽使用过度或超出预期用途(如视频流或文件共享)的代理的权利，请仅在与产品目的相关的网站上使用我们的代理。购买此商品即表示您同意我们的TOS“不退货”政策，因为产品的性质。www.iploong.com上出售的所有产品都是虚拟的，不能退货。',
            subtitle3:'可接受使用政策',
            subtitle3_content1:'禁止您使用本网站、其内容和服务:\n(a)用于任何非法目的;\n(b)教唆他人实施或者参与违法行为;\n(c)违反任何国际、联邦、省或州的法规、规则、法律或地方条例:\n(d)侵犯或侵犯我们的知识产权或他人的知识产权\n(e)基于性别、性取向、宗教、民族、种族、年龄、民族血统或残疾骚扰、虐待、俯辱、伤害、诽谤、诽谤、贬低、恐吓或歧视:\n(f)提交虚假或误导性信息;(g)上传或传输病毒或任何其他类型的恶意代码，这些代码将以或可能以任何方式使用，从而影响服务或任何相关网站、其他网站或互联网的功能或操作:\n(h) 收集或跟踪他人的个人信息:(i)垃圾邮件，钓鱼，制药，借口，蜘妹，爬行，或刮:(1)出于任何淫秽或不道德的目的;或(K)干扰或规避服务或任何相关网站、其他网站或互联网的安全功能。我们保留终止您使用本服务或任何相关网站的权利，因为您违反了任何禁止使用的规定，恐不另行通知。',
            subtitle4:'知识产权',
            subtitle4_content1:'除您拥有的内容外，根据这些条款，MIYAIP和/或其许可方拥有本网站中包含的所有知识产权和材料。\n您被授予的有限许可仅用于查看本网站上包含的材料。',
            subtitle5:'限制',
            subtitle5_content1:'您受到以下所有限制:\n在任何其他媒体上发布www.iploong.com的任何材料:\n出售、分许可和/或以其他方式将任何网站材料商业化\n公开表演和/或展示任何网站材料:\n以仟何损害或可能损害本网站的方式使用www.iploong.com;\n以任何影响用户访问本网站的方式使用www.iploong.com;\n违反适用法律法规使用www.iploong.com，或以任何方式可能对网站、任何个人或商业实体造成损害从事与本网站有关的任何数据挖掘、数据收集、数据提取或任何其他类似活动:\n使用本网站从事任何广告或营销活动。\n本网站的某些区域被限制您访问，MNYAP可能会在任何时候进一步限制您访河本网站的任何区域。您可能拥有的本网站的任何用户!D和密码都是保密的，您也必须保密。'
        },
        promotion: {
            title:'奖励推广',
            subtitle1:'返利记录',
            subtitle2:'邀请功能',
            tip1:'[满20U提现 ]',
            button1:'提现',
            tip2:'全部转到USDT余额',
            tip3:'当您邀请朋友注册时',
            tip4:'您将获取对方每次充值金额的10%返利，返利可用于提现或者直接购买产品',
            button2:'复制邀请码',
            button3:'复制邀请链接',
            tip5:'如您注册时使用了您名下其他账号的邀请链接，我们有权将邀请账号与',
            tip6:'邀请用户给您带来的返利记录',
            column1:'订单ID',
            column2:'被遨ID',
            column3:'获得返利',
            column4:'获得时间'
        }
    }
}

export const en = {
    pagination: {
        total:'Total',
        item:'Ttems'
    },
    common: {
        yes:'Confirm',
        no:'Cancel',
        success:'Success'
    },
    message: {
        register: 'Registration successful, you will be redirected',
        smscode: 'Send successfully,Please check',
        login:'Login successful and you will be redirected',
        forget:'Modification successful'
    },
    login: {
        title:'User login',
        form1:'Email Address',
        placeholder1:'Please enter your email address',
        message1:'Please enter a valid email address',
        form2:'password',
        placeholder2:"Please enter your password",
        tips:'Login means you agree',
        tips2:'Terms of Service',
        message3:'Please check the Terms of Service',
        button1:'forget the password',
        button2:'Log in',
        content:'No account?',
        content2:'Go to register'
    },
    register: {
        title:'User Registration',
        form1:'Email Address',
        placeholder1:'Please enter your email address',
        message1:'Please enter a valid email address',
        form2:'Email verification code',
        code:'Send code',
        placeholder2:'Please enter the verification code',
        message2:'Please enter the verification code',
        tip:'If you did not receive the verification code, please check the spam folder in your mailbox.',
        form3:'password',
        message3:'Please check the Terms of Service',
        placeholder3:'Please enter your password',
        form4:'Repeat password',
        placeholder4:"The passwords you entered twice do not match",
        form5:'Invite Code',
        placeholder5:'Please enter the invitation code (can be left blank)',
        tip1:'Registration means consent',
        tip2:'Terms of Service',
        button:'register',
        content:'Already have an account?',
        content2:'Log in'
    },
    forgetpassword: {
        title:'Change Password',
        form1:'Email Address',
        placeholder1:'Please enter your email address',
        message1:'Please enter a valid email address',
        form2:'Email verification code',
        code:'Send verification code',
        placeholder2:'Please enter the verification code',
        message2:'Please enter the verification code',
        tip:'If you did not receive the verification code, please check the spam folder in your mailbox.',
        form3:'password',
        message3:'Please check the Terms of Service',
        placeholder3:'Please enter your password',
        form4:'Repeat password',
        placeholder4:"The passwords you entered twice do not match",
        tip1:'agree',
        tip2:'Terms of Service',
        button:'Confirm changes',
        content:'Completed setup?',
        content2:'Log in'
    },
    nav: {
        button:'Log in',
        button1:'Register',
        item1:'Home',
        item2:'services',
        item3:'pricing'
    },
    footer: {
        title: 'With its extensive global network resources and deep business insights, IPdodo will continue to improve its product and service quality and work with its partners to expand global business.',
        subtitle1:'Policy',
        subtitle1_title1:'Miya Customer Policy',
        subtitle1_title2:'Miya Private Policy',
        subtitle2:'Friendship link',
        subtitle2_title1:'hubstudio Fingerprint Browser',
        subtitle2_title2:'mulogin Fingerprint Browser',
        subtitle2_title3:'Bit Fingerprint Browser',
        subtitle2_title4:'AdsPower',
        subtitle2_title5:'vmlogin Fingerprint Browser',
        subtitle2_title6:'yunlark Browser',
        subtitle2_title7:'nest Browser',
        subtitle2_title8:'MoreLogin Fingerprint Browser',
        subtitle2_title9:'Cross-border King (Cross-border Marketing software)',
        subtitle2_title10:'luban',
        subtitle2_title11:'firebrowser',
        item1:'tel',
        item2:'support email',
        item3:'support online time',
        item4:'office address'
    },
    home: {
        first: {
            title:'To provide you with the',
            title2:'mostprofessional',
            title3:'Data acquisition solutions',
            subtitle1:'Professional global residential proxy',
            subtitle1_detail1:'More than',
            subtitle1_detail2:'60,000,000+',
            subtitle1_detail3:'IPS',

            subtitle2:'Precise positioning of major cities around the world',
            subtitle2_detail1:'Meet',
            subtitle2_detail2:'crawler, e-commerce',
            subtitle2_detail3:'and other business needs',
            subtitle3:'Dynamic and static switch at will',
            subtitle3_detail1:'Support',
            subtitle3_detail2:'http,https,socks5',
            subtitle3_detail3:'easy to use',
        },
        second: {
            title: 'Provide reliable data acquisition solutions for your business',
            subtitle1:'Residential proxy',
            content1:'Reality-like fetching mode without IP blocking',
            subtitle2:'Leading technology',
            content2:'AI and ML based solutions for effective information capture',
            subtitle3:'Real-time crawler',
            content3:'Extract data from search engines and e- commerce sites',
            subtitle4:'Real-time crawler',
            content4:'Extract data from search engines and e-commerce sites',
            item1:'100% delivery',
            item2:'Country/region and ASN filtering',
            item3:'Adaptive parser'
        },
        third: {
            title: 'MIYAIP services in more than 200 countries around the world',
        },
        fourth: {
            title: 'More Preferential Price',
            subtitle1: 'positioning',
            subtitle1_1:' the country',
            subtitle1_type:'Dynamic Residence',
            subtitle1_content:'Charge by data, Unlimited IP number',

            subtitle2: '1 IP/month',
            subtitle2_1:'/exclusive',
            subtitle2_type:'Static residence',
            subtitle2_content:'Charge by data, Unlimited IP number',

            subtitle3: 'positioning',
            subtitle3_1:' the country',
            subtitle3_type:'Dynamic Residence',
            subtitle3_content:'Charge by data, Unlimited IP number',
            data:'Data',
            button:'Buy now'
        },
        fifth: {
            title: 'The reason why we were chosen',
            subtitle:'More than 500 countries and regions of the IP, faster speed, the best server, to give you better service',
            item1:'Faster speed',
            item2:'More stable service',
            item3:'Exclusive agency',
            item4:'Fast integration'
        }
    },
    usercenter: {
        nav: {
            menu1:'Dashboard',
            menu1_subtitle1:'Dynamic Residence',
            menu1_subtitle2:'Static Residence',
            menu2:'Dynamic Residence',
            menu2_subtitle1:'Proxy Generation-Country',
            menu2_subtitle2:'Proxy Generation',
            menu2_subtitle3:'Purchase traffic',
            menu3:'Static Residence',
            menu3_subtitle1:'Purchase Proxy',
            menu3_subtitle2:'Purchased Details',
            menu4:'Historical orders',
            menu5:'Help Center',
            menu5_subtitle1:'Help Documentation',
            menu5_subtitle2:'Terms of Service',
            menu6:'Developer API',
            menu7:'Reward Promotion'
        },
        userinfo: {
            button:'Change Password',
            content:'Account Balance',
            button1:'USDT Deposit',
            button2:'Log out',
            title:'Change Password',
            recharge: {
                title:'USDT Deposit',
                tip:'USDT transactions require confirmation time. Please wait 10-20 minutes after the transfer and submit the order number for recharge.',
                form1:'Recharge Type',
                content1:'TRC20',
                form2:'Payment Address',
                content2:'TLdKPrs3aAFx1d7628gSE3naod2MQzimng',
                code: 'Payment QR code',
                form3:'Transaction serial number',
                content3:'Please enter the transaction number',
                tip2:'After recharging, fill in the transaction serial number, and the website will display your recharged USDT balance',
                button:'submit'
            }
        },
        dashboardDy: {
            title: 'Dashboard-Dynamic Residential Proxy',
            subtitle1:'Position the country',
            button:'Proxy Generation',
            charttitle:'Total flow [Gb]',
            usedFlow:'Used flow [Gb]',
            resetFlow:'Remaining flow [Gb]',
            button2:'Purchase traffic',
            subtitle2:'Purchase trends',
            column1:'ID',
            column2:'Type',
            column3:'IP',
            column4:'Location',
            column5:'Date',
            column6:'User-Agent'
        },
        dashboardStatic: {
            title: 'Dashboard-Static Residential Proxy',
            subtitle1:'All proxy',
            unit:'piece',
            subtitle2:'Exclusive proxy',
            subtitle3:'Shared proxy',
            tableTitle:'Purchase trends',
            button:'More',
            column1:'Socks5 QR code',
            column2:'Expiration time',
            column3:'type',
            column4:'Original IP(Socks5)',
            column5:'Original IP(http)',
            column6:'Transit proxy(Socks5)',
        },
        proxycity: {
            form1:'Pool type',
            placeholder:'Please select',
            countryform:'Global Random',
            IPform:'Change each time you request',
            form2:'Country',
            min:'minutes',
            form3:'Province/State',
            form4:'City',
            form5:'Fixed IP switching time',
            form6:'Generate Type',
            form7:'Num',
            subtitle:'API switch proxy button',
            tip:'',
            switch:'If necessary, click',
            button1:'Generate',
            button2:'Export to API',
            copy:'Copy',
            cityform:'Random Selection',
            tip2:'Enter or paste the proxy text to generate a QR code (only one proxy text can be converted to a QR code at a time)',
            button3:'Generate QR code',
            tip3:'Generate a socks5 QR code (can be scanned directly with Shadowrockt)',
            tip4:'No QR code yet',
            title:'Proxy Generation',
            button4:'Purchase traffic',
            charttitle:'Total flow [Gb]',
            usedFlow:'Used flow [Gb]',
            resetFlow:'Remaining flow [Gb]',
            button:'Go and find out',
            button_title:'Please contact us for more special packages',
            subtitle9:'Time variability',
        },
        purchasetraffic: {
            title:'Purchase traffic',
            content1:'Location country',
            content2:'Never expires',
            content3:'Dedicated IP pool',
            content4:'2 super large IP pools, with a total of over 60 million IPs',
            content5:'Unlimited concurrency',
            content6:'Variable aging',
            content7:'Not supported',
            tip:'Max. 100G',
            subtitle1:'category',
            subtitle2:'unit price',
            subtitle3:'Duration',
            subtitle4:'IP Pool',
            subtitle5:'Number of dynamic IP pools',
            subtitle6:'Concurrency',
            subtitle7:'City Positioning',
            subtitle8:'flow',
            subtitle9:'Time variability',
            content11:'Location city',
            content12:'Never expires',
            content13:'Dedicated IP pool',
            content14:'2 super large IP pools, with a total of over 60 million IPs',
            content15:'Unlimited concurrency',
            content16:'Variable aging',
            content17:'Not supported',
            tip2:'No traffic category selected',
            label:'Discount Code',
            tip3:'Please enter the discount code',
            tip4:'Targeting selected',
            tip5:'Purchase traffic',
            tip6:'Buy it',
            tip7:'Country',
            tip8:'City',
            button:'Go and find out',
            button_title:'Please contact us for more special packages'
        },
        pay: {
            title:'Total amount',
            button1:'USDT balance',
            button2:'Other payment',
            pay1:'Alipay',
            pay2:'WeChat',
            button3:'Confirm payment',
            button4:'Insufficient balance',
            button5:'Cancle'
        },
        purchaseproxy: {
            title:'Purchase roxy',
            subtitle1:'Demand Countries',
            subtitle2:'IP authorization type',
            subtitle3:'IP Purchase Duration',
            subtitle4:'Number of IPs purchased',
            subtitle4_tip:'(Maximum quantity 100)',
            subtitle5:'Discount Code',
            subtitle2_1:'Exclusive',
            subtitle2_2:'shared',
            subtitle2_tip:'Exclusive unit price',
            subtitle2_tip1:' /IP/Month',
            unit:'Day',
            subtitle5_content:'Please enter the discount code',
            content1:'IP selected',
            unit2:'Item'
        },
        historyorder: {
            title:'Historical orders',
            subtitle1:'All [Orders]',
            subtitle2:'Paid [order]',
            subtitle3:'Unpaid [order]',
            select1:'ALL',
            select2:'Paid',
            select3:'Unpaid',
            placeholder:'Please enter the id to query',
            column1:'Order ID',
            column2:'Order Name',
            column3:'lump sum ',
            column4:'Order Status',
            column5:'Order Time',
            column6:'Payment Time'
        },
        serviceterms: {
            title:'Terms of Service',
            subtitle1:'introduce',
            subtitle1_content1:`These Website Standard Terms and Conditions written on this webpage shall govern your use of our website, IPLOONG accessible at www.iploong.com.\nThese Terms shall fully apply and affect your use of this website. By using this website, you are agreeing to be bound by all the terms and conditions written herein. If you do not agree with any of this Website's Standard Terms and Conditions, you must not use this website.\nIPLOONG does not knowingly collect personal information, either online or offline, from anyone under the age of 13. If you are under the age of 18, you may use www.iploong.com only with the permission of a parent or guardian.`,
            subtitle2:'Refund Policy',
            subtitle2_content1:`These proxies are active from the time you receive them, all proxies are tested prior to delivery and are fully functional upon delivery. Proxies are designated as Datacenter or Residential based on the product name and description and are not determined by the customer. We are not responsible for bans due to misuse and incorrect setup during the launch period. We reserve the right to deactivate proxies for excessive bandwidth usage or beyond the intended use such as video streaming or file sharing, please only use our proxies on sites related to the product purpose. By purchasing this item you agree to our TOS "No Returns" policy due to the nature of the product. All products sold on www.iploong.com are virtual and cannot be returned.`,
            subtitle3:'Acceptable Use Policy',
            subtitle3_content1:`You are prohibited from using the site, its content, and services:\n(a) for any unlawful purpose;\n(b) to solicit others to commit or participate in illegal acts;\n(c) to violate any international, federal, provincial or state regulations, rules, laws, or local ordinances;\n(d) to infringe upon or violate our intellectual property rights or the intellectual property rights of others;\n(e) to harass, abuse, disparage, defame, slander, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability;\n(f) to submit false or misleading information;\n(g) to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Service or of any related website, other websites, or the Internet;\n(h) to collect or track the personal information of others;\n(i) to spam, phish, pharm, pretext, spider, crawl, or scrape;\n(i) for any obscene or immoral purpose; or\n(k) to interfere with or circumvent the security features of the Service or of any related website, other websites, or the Internet. We reserve the right to terminate your use of the Service or any related website, without prior notice, for violating any of the prohibited uses.`,
            subtitle4:'intellectual property',
            subtitle4_content1:`Other than the content you own, under these Terms, IPLOONG and/or its licensors own all the intellectual property rights and materials contained in this Website.\nYou are granted limited license solely for viewing the materials contained on this Website.`,
            subtitle5:'limit',
            subtitle5_content1:`You are subject to all of the following restrictions:\nPublish any material from www.iploong.com in any other media:\nSell, sublicense and/or otherwise commercialize any Website material\nPublicly perform and/or display any Website material:\nUse www.iploong.com in any way that damages or may damage the Website;\nUse www.iploong.com in any way that affects the access of users to the Website;\nUse www.iploong.com contrary to applicable laws and regulations, or in any way that may cause damage to the Website, any person or business entity Engage in any data mining, data harvesting, data extracting or any other similar activity in relation to the Website:\nUse the Website to engage in any advertising or marketing activities.\nCertain areas of the Website are restricted from access by you and MNYAP may further restrict access by you to any areas of the Website at any time. Any user ID and password you may have for the Website are confidential and you must keep them confidential.`
        },
        promotion: {
            title:'Reward Promotion',
            subtitle1:'Rebate Record',
            subtitle2:'Invite function',
            tip1:'[Withdraw after 20U]',
            button1:'Withdrawal',
            tip2:'All transferred to USDT balance',
            tip3:'When you invite friends to register',
            tip4:`You will receive a 10% rebate on each top-up amount, which can be used to withdraw cash or purchase products directly.`,
            button2:'Copy invitation code',
            button3:'Copy invitation link',
            tip5:'If you use an invitation link from another account under your name when registering, we have the right to',
            tip6:'The rebate record brought to you by inviting users',
            column1:'Order ID',
            column2:'Invited ID',
            column3:'Get rebates',
            column4:'Get time'
        }
    }
}