export const zh = {
    common: {
        yes:'确认',
        no:'取消',
        success:'成功'
    },
    pagination: {
        total:'共',
        item:'条'
    },
    message: {
        register: '注册成功即将跳转',
        smscode: '发送成功,注意查收',
        login:'登录成功即将跳转',
        forget:'修改成功'
    },
    login: {
        title:'用户登录',
        form1:'邮箱地址',
        placeholder1:'请输入邮箱',
        message1:'请输入正确的邮箱',
        form2:'密码',
        placeholder2:"请输入密码",
        tips:'登录即代表同意',
        tips2:'服务条款',
        button1:'忘记密码',
        message3:'请勾选服务条款',
        button2:'登录',
        content:'没有账户?',
        content2:'去注册'
    },
    register: {
        title:'用户注册',
        form1:'邮箱地址',
        placeholder1:'请输入邮箱',
        message1:'请输入正确的邮箱',
        form2:'邮箱验证码',
        code:'发送验证码',
        placeholder2:'请输入验证码',
        message2:'请输入验证码',
        message3:'请勾选服务条款',
        tip:'如果没有收到验证码，请检查邮箱的垃圾箱',
        form3:'密码',
        placeholder3:'请输入密码',
        form4:'重复密码',
        placeholder4:"两次输入的密码不一致",
        form5:'邀请码',
        placeholder5:'请输入邀请码(可留空)',
        tip1:'注册即代表同意',
        tip2:'服务条款',
        button:'注册',
        content:'已有账号?',
        content2:'登录'
    },
    forgetpassword: {
        title:'修改密码',
        form1:'邮箱地址',
        placeholder1:'请输入邮箱',
        message1:'请输入正确的邮箱',
        form2:'邮箱验证码',
        code:'发送验证码',
        placeholder2:'请输入验证码',
        message2:'请输入验证码',
        message3:'请勾选服务条款',
        tip:'如果没有收到验证码，请检查邮箱的垃圾箱',
        form3:'密码',
        placeholder3:'请输入密码',
        form4:'重复密码',
        placeholder4:"两次输入的密码不一致",
        tip1:'同意',
        tip2:'服务条款',
        button:'确认修改',
        content:'已完成设置?',
        content2:'登录'
    },
    nav: {
        button:'登录',
        button1:'注册',
        item1:'主页',
        item2:'服务',
        item3:'价格'
    },
    footer: {
        title: '凭借全球广泛的网络资源布局和深刻的业务洞察，IPdodo将不断精进产品与服务品质，与合作伙伴坚定共拓全球化业务',
        subtitle1:'政策',
        subtitle1_title1:'Miya用户协议',
        subtitle1_title2:'Miya隐私协议',
        subtitle2:'友情链接',
        subtitle2_title1:'hubstudio Fingerprint Browser',
        subtitle2_title2:'mulogin Fingerprint Browser',
        subtitle2_title3:'Bit Fingerprint Browser',
        subtitle2_title4:'AdsPower',
        subtitle2_title5:'vmlogin Fingerprint Browser',
        subtitle2_title6:'yunlark Browser',
        subtitle2_title7:'nest Browser',
        subtitle2_title8:'MoreLogin Fingerprint Browser',
        subtitle2_title9:'Cross-border King (Cross-border Marketing software)',
        subtitle2_title10:'luban',
        subtitle2_title11:'firebrowser',
        item1:'电话',
        item2:'邮箱',
        item3:'在线时间',
        item4:'办公地址'
    },
    home: {
        first: {
            title:'为您提供',
            title2:'最专业',
            title3:'数据采集​​解决方案',
            subtitle1:'专业的全球住宅代理',
            subtitle1_detail1:'超过',
            subtitle1_detail2:'60,000,000+',
            subtitle1_detail3:'IPS',

            subtitle2:'全球主要城市精准定位',
            subtitle2_detail1:'参与',
            subtitle2_detail2:'爬虫，电子商务',
            subtitle2_detail3:'以及其他业务需求',
            subtitle3:'动静随意切换',
            subtitle3_detail1:'支持',
            subtitle3_detail2:'http,https,socks5',
            subtitle3_detail3:'便于使用',
        },
        second: {
            title: '为您的企业提供可靠的数据采集解决方案',
            subtitle1:'住宅代理',
            content1:'无需IP封锁的真实抓取模式',
            subtitle2:'领先技术',
            content2:'基于人工智能和机器学习的解决方案，可有效捕获信息',
            subtitle3:'实时爬虫',
            content3:'从搜索引擎和电子商务网站提取数据',
            subtitle4:'实时爬虫',
            content4:'从搜索引擎和电子商务网站提取数据',
            item1:'100% 交付',
            item2:'国家/地区和 ASN 筛选',
            item3:'自适应解析器'
        },
        third: {
           title: 'MIYAIP服务全球200多个国家',
        },
        fourth: {
            title: '更优惠的价格',
            subtitle1: '定位',
            subtitle1_1:'地区',
            subtitle1_type:'动态住宅',
            subtitle1_content:'按流量计费，不限IP数量',

            subtitle2: '1 IP/月',
            subtitle2_1:'/独享',
            subtitle2_type:'静态住宅',
            subtitle2_content:'按流量计费，不限IP数量',

            subtitle3: '定位',
            subtitle3_1:'地区',
            subtitle3_type:'动态住宅',
            subtitle3_content:'按流量计费，不限IP数量',
            data:'数据',
            button:'立刻购买'
        },
        fifth: {
            title: '选择我们的理由',
            subtitle:'超过500个国家和地区的IP，更快的速度，最好的服务器，给您更好的服务',
            item1:'速度更快',
            item2:'更稳定的服务',
            item3:'独家代理',
            item4:'快速集成'
        }
    },
    usercenter: {
        
        nav: {
            menu1:'仪表盘',
            menu1_subtitle1:'动态住宅',
            menu1_subtitle2:'静态住宅',
            menu2:'动态住宅',
            menu2_subtitle1:'代理生成-国家',
            menu2_subtitle2:'代理生成-城市',
            menu2_subtitle3:'购买流量',
            menu3:'静态住宅',
            menu3_subtitle1:'购买代理',
            menu3_subtitle2:'已购明细',
            menu4:'历史订单',
            menu5:'帮助中心',
            menu5_subtitle1:'帮助文档',
            menu5_subtitle2:'服务条款',
            menu6:'开发者API',
            menu7:'奖励推广'
        },
        userinfo: {
            button:'修改密码',
            content:'账户余额',
            button1:'USDT充值',
            button2:'退出登录',
            title:'修改密码',
            recharge: {
                title:'USDT充值',
                tip:'USDT交易需要确认时间，i请转账后等待10-20分钟后提交单号充值',
                form1:'充值类型',
                content1:'TRC20',
                form2:'付款地址',
                content2:'TLdKPrs3aAFx1d7628gSE3naod2MQzimng',
                code: '付款地址二维码',
                form3:'交易流水号',
                content3:'请输入流水交易号',
                tip2:'充值后填写交易流水号，网站会显示您充值的USDT余额',
                button:'提交'
            }
        },
        dashboardDy: {
            title: '仪表板-动态住宅代理',
            subtitle1:'定位国家',
            button:'代理生成',
            charttitle:'总流量 [Gb]',
            usedFlow:'已使用流量 [Gb]',
            resetFlow:'剩余流量 [Gb]',
            button2:'购买流量',
            subtitle2:'流量使用趋势',
            column1:'ID',
            column2:'类型',
            column3:'IP',
            column4:'地点',
            column5:'日期',
            column6:'User-Agent'
        },
        dashboardStatic: {
            title: '仪表板-静态住宅代理',
            subtitle1:'全部代理',
            subtitle2:'独享代理',
            subtitle3:'共享代理',
            tableTitle:'流量使用趋势',
            button:'更多',
            column1:'Socks5 二维码',
            column2:'过期时间',
            column3:'类型',
            column4:'原始IP(Socks5)',
            column5:'原始IP(http)',
            column6:'中转代理(Socks5)',
        }
    }
}

export const en = {
    pagination: {
        total:'Total',
        item:'Ttems'
    },
    common: {
        yes:'Confirm',
        no:'Cancel',
        success:'Success'
    },
    message: {
        register: 'Registration successful, you will be redirected',
        smscode: 'Send successfully,Please check',
        login:'Login successful and you will be redirected',
        forget:'Modification successful'
    },
    login: {
        title:'User login',
        form1:'Email Address',
        placeholder1:'Please enter your email address',
        message1:'Please enter a valid email address',
        form2:'password',
        placeholder2:"Please enter your password",
        tips:'Login means you agree',
        tips2:'Terms of Service',
        message3:'Please check the Terms of Service',
        button1:'forget the password',
        button2:'Log in',
        content:'No account?',
        content2:'Go to register'
    },
    register: {
        title:'User Registration',
        form1:'Email Address',
        placeholder1:'Please enter your email address',
        message1:'Please enter a valid email address',
        form2:'Email verification code',
        code:'Send code',
        placeholder2:'Please enter the verification code',
        message2:'Please enter the verification code',
        tip:'If you did not receive the verification code, please check the spam folder in your mailbox.',
        form3:'password',
        message3:'Please check the Terms of Service',
        placeholder3:'Please enter your password',
        form4:'Repeat password',
        placeholder4:"The passwords you entered twice do not match",
        form5:'Invite Code',
        placeholder5:'Please enter the invitation code (can be left blank)',
        tip1:'Registration means consent',
        tip2:'Terms of Service',
        button:'register',
        content:'Already have an account?',
        content2:'Log in'
    },
    forgetpassword: {
        title:'Change Password',
        form1:'Email Address',
        placeholder1:'Please enter your email address',
        message1:'Please enter a valid email address',
        form2:'Email verification code',
        code:'Send verification code',
        placeholder2:'Please enter the verification code',
        message2:'Please enter the verification code',
        tip:'If you did not receive the verification code, please check the spam folder in your mailbox.',
        form3:'password',
        message3:'Please check the Terms of Service',
        placeholder3:'Please enter your password',
        form4:'Repeat password',
        placeholder4:"The passwords you entered twice do not match",
        tip1:'agree',
        tip2:'Terms of Service',
        button:'Confirm changes',
        content:'Completed setup?',
        content2:'Log in'
    },
    nav: {
        button:'Log in',
        button1:'Register',
        item1:'Home',
        item2:'services',
        item3:'pricing'
    },
    footer: {
        title: 'With its extensive global network resources and deep business insights, IPdodo will continue to improve its product and service quality and work with its partners to expand global business.',
        subtitle1:'Policy',
        subtitle1_title1:'Miya Customer Policy',
        subtitle1_title2:'Miya Private Policy',
        subtitle2:'Friendship link',
        subtitle2_title1:'hubstudio Fingerprint Browser',
        subtitle2_title2:'mulogin Fingerprint Browser',
        subtitle2_title3:'Bit Fingerprint Browser',
        subtitle2_title4:'AdsPower',
        subtitle2_title5:'vmlogin Fingerprint Browser',
        subtitle2_title6:'yunlark Browser',
        subtitle2_title7:'nest Browser',
        subtitle2_title8:'MoreLogin Fingerprint Browser',
        subtitle2_title9:'Cross-border King (Cross-border Marketing software)',
        subtitle2_title10:'luban',
        subtitle2_title11:'firebrowser',
        item1:'tel',
        item2:'support email',
        item3:'support online time',
        item4:'office address'
    },
    home: {
        first: {
            title:'To provide you with the',
            title2:'mostprofessional',
            title3:'Data acquisition solutions',
            subtitle1:'Professional global residential proxy',
            subtitle1_detail1:'More than',
            subtitle1_detail2:'60,000,000+',
            subtitle1_detail3:'IPS',

            subtitle2:'Precise positioning of major cities around the world',
            subtitle2_detail1:'Meet',
            subtitle2_detail2:'crawler, e-commerce',
            subtitle2_detail3:'and other business needs',
            subtitle3:'Dynamic and static switch at will',
            subtitle3_detail1:'Support',
            subtitle3_detail2:'http,https,socks5',
            subtitle3_detail3:'easy to use',
        },
        second: {
            title: 'Provide reliable data acquisition solutions for your business',
            subtitle1:'Residential proxy',
            content1:'Reality-like fetching mode without IP blocking',
            subtitle2:'Leading technology',
            content2:'AI and ML based solutions for effective information capture',
            subtitle3:'Real-time crawler',
            content3:'Extract data from search engines and e- commerce sites',
            subtitle4:'Real-time crawler',
            content4:'Extract data from search engines and e-commerce sites',
            item1:'100% delivery',
            item2:'Country/region and ASN filtering',
            item3:'Adaptive parser'
        },
        third: {
            title: 'MIYAIP services in more than 200 countries around the world',
        },
        fourth: {
            title: 'More Preferential Price',
            subtitle1: 'positioning',
            subtitle1_1:' the country',
            subtitle1_type:'Dynamic Residence',
            subtitle1_content:'Charge by data, Unlimited IP number',

            subtitle2: '1 IP/month',
            subtitle2_1:'/exclusive',
            subtitle2_type:'Static residence',
            subtitle2_content:'Charge by data, Unlimited IP number',

            subtitle3: 'positioning',
            subtitle3_1:' the country',
            subtitle3_type:'Dynamic Residence',
            subtitle3_content:'Charge by data, Unlimited IP number',
            data:'Data',
            button:'Buy now'
        },
        fifth: {
            title: 'The reason why we were chosen',
            subtitle:'More than 500 countries and regions of the IP, faster speed, the best server, to give you better service',
            item1:'Faster speed',
            item2:'More stable service',
            item3:'Exclusive agency',
            item4:'Fast integration'
        }
    },
    usercenter: {
        nav: {
            menu1:'Dashboard',
            menu1_subtitle1:'Dynamic Residence',
            menu1_subtitle2:'Static Residence',
            menu2:'Dynamic Residence',
            menu2_subtitle1:'Proxy Generation-Country',
            menu2_subtitle2:'Proxy Generation-City',
            menu2_subtitle3:'Purchase traffic',
            menu3:'Static Residence',
            menu3_subtitle1:'Purchase Proxy',
            menu3_subtitle2:'Purchased Details',
            menu4:'Historical orders',
            menu5:'Help Center',
            menu5_subtitle1:'Help Documentation',
            menu5_subtitle2:'Terms of Service',
            menu6:'Developer API',
            menu7:'Reward Promotion'
        },
        userinfo: {
            button:'Change Password',
            content:'Account Balance',
            button1:'USDT Deposit',
            button2:'Log out',
            title:'Change Password',
            recharge: {
                title:'USDT Deposit',
                tip:'USDT transactions require confirmation time. Please wait 10-20 minutes after the transfer and submit the order number for recharge.',
                form1:'Recharge Type',
                content1:'TRC20',
                form2:'Payment Address',
                content2:'TLdKPrs3aAFx1d7628gSE3naod2MQzimng',
                code: 'Payment QR code',
                form3:'Transaction serial number',
                content3:'Please enter the transaction number',
                tip2:'After recharging, fill in the transaction serial number, and the website will display your recharged USDT balance',
                button:'submit'
            }
        },
        dashboardDy: {
            title: 'Dashboard-Dynamic Residential Proxy',
            subtitle1:'Position the country',
            button:'Proxy Generation',
            charttitle:'Total flow [Gb]',
            usedFlow:'Used flow [Gb]',
            resetFlow:'Remaining flow [Gb]',
            button2:'Purchase traffic',
            subtitle2:'Purchase trends',
            column1:'ID',
            column2:'Type',
            column3:'IP',
            column4:'Location',
            column5:'Date',
            column6:'User-Agent'
        },
        dashboardStatic: {
            title: 'Dashboard-Static Residential Proxy',
            subtitle1:'All proxy',
            subtitle2:'Exclusive proxy',
            subtitle3:'Shared proxy',
            tableTitle:'Purchase trends',
            button:'More',
            column1:'Socks5 QR code',
            column2:'Expiration time',
            column3:'type',
            column4:'Original IP(Socks5)',
            column5:'Original IP(http)',
            column6:'Transit proxy(Socks5)',
        }
    }
}